version: '3'

services:
#  database:
#    container_name: preonb_db
#    image: mysql:8.0.22
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_PASSWORD: root
#      TZ: 'Asia/Seoul'
#    ports:
#      - "13306:3306"
#    volumes:
#      - ./mysql/conf.d:/etc/mysql/conf.d
#    command:
#      - "mysqld"
#      - "--character-set-server=utf8mb4"
#      - "--collation-server=utf8mb4_unicode_ci"
#    networks:
#      - preon_net

  application:
    container_name: preonb
    image: preonb:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - .env
    networks:
      - preon_net

  nginx:
    container_name: nginx
    image: jonghuni/preonb-nginx
    ports:
      - 80:80
    depends_on:
      - application

networks:
  preon_net: {}
