spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  base-package: com.example.wantedpreonboardingbackend
  path: /api/**
  version: 1.0.0
